(() => {
const D=window.APP_DATA,W=D.workouts,I=D.exerciseInfo,DB='dm-strength-v1',STORE='workouts';
let db,person='David',active=null,blockIndex=0,draft={},timerInt=null,deferredPrompt=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1800)};
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function all(){return new Promise((res,rej)=>{const t=db.transaction(STORE,'readonly'),r=t.objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function put(o){return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(o);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function clear(){return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).clear();t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function show(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='progressView')renderProgress()}
function target(e){return e.id==='pushups'?`${e.sets} sets · leave 1–2 RIR`:`${e.sets} × ${e.min}–${e.max} ${e.unit}`}
function home(){const h=$('#workoutCards');h.innerHTML='';Object.entries(W).forEach(([day,w])=>{const b=document.createElement('button');b.className='workout-card';b.innerHTML=`<strong>${w.name}</strong><div class="meta">${w.blocks.length} paired blocks · ${w.blocks.reduce((n,x)=>n+x.exercises.length,0)} exercises</div><div class="blocks">${w.blocks.map(x=>`<span class="pill">${x.label}: ${x.exercises.map(e=>e.name).join(' + ')}</span>`).join('')}</div>`;b.onclick=()=>start(day);h.appendChild(b)})}
function start(day){active={day,...W[day],startedAt:new Date().toISOString()};blockIndex=0;draft={};$('#workoutPerson').textContent=person.toUpperCase();$('#workoutTitle').textContent=W[day].name;nav();renderBlock();show('workoutView')}
function nav(){const n=$('#blockNav');n.innerHTML='';active.blocks.forEach((b,i)=>{const x=document.createElement('button');x.textContent=b.label;x.classList.toggle('active',i===blockIndex);x.onclick=()=>{blockIndex=i;nav();renderBlock()};n.appendChild(x)})}
const dk=(id,n)=>`${id}:${n}`;function gd(e,n){const k=dk(e.id,n);if(!draft[k])draft[k]={weight:'',reps:'',rir:'2',done:false};return draft[k]}
async function lastSession(id){const a=(await all()).filter(w=>w.person===person&&(w.sets||[]).some(s=>s.exerciseId===id)).sort((a,b)=>new Date(b.date)-new Date(a.date));return a.length?a[0].sets.filter(s=>s.exerciseId===id):null}
function rec(e,l){if(!l||!l.length)return'Start light and leave about 2–3 clean reps in reserve.';if(e.id==='pushups')return'Keep 1–2 RIR. Add reps or reduce incline when all sets are strong.';const ok=l.length>=e.sets&&l.slice(0,e.sets).every(s=>Number(s.reps)>=e.max&&Number(s.rir)>=1&&Number(s.rir)<=3);if(ok)return'Ready to progress: increase by the smallest available weight increment next time.';if(l.some(s=>Number(s.reps)<e.min))return'Keep or slightly reduce weight until every set reaches the bottom of the range cleanly.';return'Keep this weight and build reps toward the top of the range.'}
async function renderBlock(){stopTimer();const b=active.blocks[blockIndex],rounds=Math.max(...b.exercises.map(e=>e.sets)),body=$('#workoutBody');body.innerHTML=`<div class="card"><div class="block-header"><div><div class="eyebrow">SUPERSET ${b.label}</div><div class="block-title">${b.exercises.map(e=>e.name).join(' + ')}</div></div><div class="muted">${rounds} rounds</div></div><div id="exercisePanels"></div><div id="timer" class="timer"><div><div class="eyebrow" style="color:#cbd5e1">REST</div><div id="timerTime" class="timer-time"></div></div><div><button id="timerSkip">Skip</button> <button id="timerPlus">+30s</button></div></div><div class="next-card"><button id="prevBlock" class="secondary">Previous</button><button id="nextBlock" class="primary">${blockIndex===active.blocks.length-1?'Finish workout':'Next block'}</button></div></div>`;const h=$('#exercisePanels');
for(const e of b.exercises){const l=await lastSession(e.id),lt=l&&l.length?l.map(s=>`${s.weight?`${s.weight} lb × `:''}${s.reps}${e.unit==='sec'?' sec':''}`).join(' · '):'No previous workout logged yet.';const p=document.createElement('div');p.className='exercise-panel';p.innerHTML=`<div class="exercise-name"><span class="exercise-code">${e.code}</span>${e.name}</div><div class="target">${target(e)}</div><div class="last"><strong>Last time:</strong> ${lt}</div><div class="recommend">${rec(e,l)}</div><div class="set-list"></div><details class="details"><summary>How to do this exercise</summary><div class="detail-grid"><div><strong>Equipment</strong>${I[e.id]?.equipment||''}</div><div><strong>Setup</strong>${I[e.id]?.setup||''}</div><div><strong>How</strong>${I[e.id]?.how||''}</div><div><strong>Form cues</strong>${I[e.id]?.cues||''}</div><div><strong>Common mistakes</strong>${I[e.id]?.mistakes||''}</div></div></details>`;const sl=p.querySelector('.set-list');
for(let n=1;n<=e.sets;n++){const d=gd(e,n);if(!d.weight&&l&&l[n-1]?.weight)d.weight=l[n-1].weight;const r=document.createElement('div');r.className='set-row';r.innerHTML=`<div class="set-num">S${n}</div><label>Weight<input inputmode="decimal" data-f="weight" value="${d.weight||''}" placeholder="lb"></label><label>${e.unit==='sec'?'Seconds':'Reps'}<input inputmode="numeric" data-f="reps" value="${d.reps||''}" placeholder="${e.unit==='sec'?'45':'10'}"></label><label>RIR<input inputmode="numeric" data-f="rir" value="${d.rir||'2'}"></label><button class="complete-set ${d.done?'done':''}">${d.done?'✓':'○'}</button>`;r.querySelectorAll('input').forEach(inp=>inp.oninput=()=>gd(e,n)[inp.dataset.f]=inp.value.trim());r.querySelector('.complete-set').onclick=()=>{const dd=gd(e,n),rv=Number(r.querySelector('[data-f="reps"]').value);if(!rv||rv<1){toast('Enter reps or seconds first.');return}dd.weight=r.querySelector('[data-f="weight"]').value.trim();dd.reps=rv;dd.rir=Math.max(0,Math.min(10,Number(r.querySelector('[data-f="rir"]').value)||2));dd.done=!dd.done;r.querySelector('.complete-set').classList.toggle('done',dd.done);r.querySelector('.complete-set').textContent=dd.done?'✓':'○';if(dd.done)timer(b.rest)};sl.appendChild(r)}h.appendChild(p)}
$('#prevBlock').disabled=blockIndex===0;$('#prevBlock').onclick=()=>{if(blockIndex){blockIndex--;nav();renderBlock()}};$('#nextBlock').onclick=()=>{if(blockIndex===active.blocks.length-1)finish();else{blockIndex++;nav();renderBlock()}}}
function timer(sec){stopTimer();const e=$('#timer');if(!e)return;let left=sec;e.classList.add('show');const paint=()=>$('#timerTime').textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;paint();timerInt=setInterval(()=>{left--;paint();if(left<=0){stopTimer();toast('Rest complete')}},1000);$('#timerSkip').onclick=stopTimer;$('#timerPlus').onclick=()=>{left+=30;paint()}}
function stopTimer(){if(timerInt){clearInterval(timerInt);timerInt=null}const e=$('#timer');if(e)e.classList.remove('show')}
async function finish(){const sets=[];for(const b of active.blocks)for(const e of b.exercises)for(let n=1;n<=e.sets;n++){const d=gd(e,n);if(d.done&&Number(d.reps)>0)sets.push({exerciseId:e.id,exerciseName:e.name,block:b.label,set:n,weight:d.weight,reps:Number(d.reps),rir:Number(d.rir||2)})}if(!sets.length){toast('Complete at least one set first.');return}await put({id:`${Date.now()}-${Math.random().toString(36).slice(2)}`,person,day:active.day,name:active.name,date:new Date().toISOString(),startedAt:active.startedAt,sets});toast('Workout saved');$('#progressPerson').value=person;show('progressView')}
function names(){const m=new Map;Object.values(W).forEach(w=>w.blocks.forEach(b=>b.exercises.forEach(e=>m.set(e.id,e.name))));return [...m.entries()]}
async function renderProgress(){const pp=$('#progressPerson').value,s=$('#progressExercise');if(!s.options.length)names().forEach(([id,n])=>{const o=document.createElement('option');o.value=id;o.textContent=n;s.appendChild(o)});const id=s.value||names()[0][0],a=(await all()).filter(w=>w.person===pp).sort((a,b)=>new Date(b.date)-new Date(a.date)),sessions=a.map(w=>({w,sets:w.sets.filter(x=>x.exerciseId===id)})).filter(x=>x.sets.length);chart(sessions.slice().reverse());const h=$('#historyList');h.innerHTML='';sessions.slice(0,12).forEach(({w,sets})=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<strong>${new Date(w.date).toLocaleDateString()}</strong><div class="muted">${w.name}</div><div class="meta">${sets.map(x=>`${x.weight?`${x.weight} lb × `:''}${x.reps} @ ${x.rir} RIR`).join(' · ')}</div>`;h.appendChild(d)});if(!sessions.length)h.innerHTML='<div class="card muted">No history yet.</div>'}
function chart(s){const c=$('#progressChart'),e=$('#progressEmpty');if(!s.length){c.style.display='none';e.style.display='block';return}c.style.display='block';e.style.display='none';const ctx=c.getContext('2d'),w=c.clientWidth||600,h=260,dpr=Math.min(devicePixelRatio||1,2);c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const p=s.map(({w,sets})=>({v:Math.max(...sets.map(x=>Number(x.weight)||Number(x.reps)||0))})),max=Math.max(...p.map(x=>x.v),1),min=Math.min(...p.map(x=>x.v),0),pad=30,x=i=>pad+(w-pad-15)*(p.length===1?.5:i/(p.length-1)),y=v=>h-pad-(h-pad-20)*((v-min)/(max-min||1));ctx.strokeStyle='#d1d5db';ctx.beginPath();ctx.moveTo(pad,10);ctx.lineTo(pad,h-pad);ctx.lineTo(w-10,h-pad);ctx.stroke();ctx.strokeStyle='#111827';ctx.lineWidth=2;ctx.beginPath();p.forEach((q,i)=>i?ctx.lineTo(x(i),y(q.v)):ctx.moveTo(x(i),y(q.v)));ctx.stroke();ctx.fillStyle='#111827';p.forEach((q,i)=>{ctx.beginPath();ctx.arc(x(i),y(q.v),4,0,Math.PI*2);ctx.fill()})}
function guide(q=''){const h=$('#guideList');h.innerHTML='';names().filter(([,n])=>!q||n.toLowerCase().includes(q.toLowerCase())).forEach(([id,n])=>{const d=document.createElement('details');d.className='guide-item';d.innerHTML=`<summary>${n}</summary><div class="detail-grid"><div><strong>Equipment</strong>${I[id]?.equipment||''}</div><div><strong>Setup</strong>${I[id]?.setup||''}</div><div><strong>How</strong>${I[id]?.how||''}</div><div><strong>Form cues</strong>${I[id]?.cues||''}</div><div><strong>Common mistakes</strong>${I[id]?.mistakes||''}</div></div>`;h.appendChild(d)})}
async function exportData(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),workouts:await all()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`strength-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500);toast('Backup exported')}
async function importData(f){try{const d=JSON.parse(await f.text());if(!Array.isArray(d.workouts))throw 0;await clear();for(const w of d.workouts)await put(w);toast('Backup imported');renderProgress()}catch{toast('Could not import backup.')}}
function wire(){$('#personPicker').onclick=e=>{const b=e.target.closest('[data-person]');if(!b)return;person=b.dataset.person;$$('#personPicker button').forEach(x=>x.classList.toggle('selected',x===b))};$('#backHome').onclick=()=>show('homeView');$('#finishWorkout').onclick=finish;$$('.nav-btn').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#progressPerson').onchange=renderProgress;$('#progressExercise').onchange=renderProgress;$('#guideSearch').oninput=e=>guide(e.target.value);$('#exportData').onclick=exportData;$('#importData').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}}}
(async()=>{try{await openDB()}catch{toast('Local storage unavailable.')}home();guide();wire();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})})()
})();